### ISSUE TITLE
regarding translation of text

### ISSUE THREAD

**Issue by nagapoornima22** [SudharshanShanmugasundaram/Neural-Machine-Translation#1]
Hi, thanks for providing a good tutorial , instead of generating the src, target, predicted. 

can we edit the code such that it accepts multiple user inputs and predict the target language .

please help me regarding this. Kindly waiting for your response.

Thanks & Regards

**Comment by SudharshanShanmugasundaram** [comment]
Yeah, you can very well modify the code to accept multiple user inputs. Once the model has trained then no need to have src, target and prediction, and you can just feed the input to get the translation
